title = "Corejourney"
baseURL = 'https://corejourney.ca'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Articles in the same category:"
  favicon = "/favicon.png"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true